#!/usr/bin/env node
/**
 * tooling/generators/app/index.js — DTE app scaffolder.
 *
 * Stamps out a brand-new app workspace under apps/ with the full
 * DTE starter set: package.json (workspace deps, @dte/shared), a
 * self-contained tsconfig extending the repo base, a Vite config
 * using @dte/config-vite presets, an index.html shell with the
 * brand topbar/hero skeleton, a styles.css preloaded with brand
 * tokens, and a src/ scaffold (main.ts, lib/, components/, pages/,
 * hooks/ barrels).
 *
 * Usage:
 *   node tooling/generators/app/index.js <name> [--type web] [--dry-run]
 *
 * Types:
 *   web      vanilla TS + Vite surface (default — same family as landing)
 *
 * The generator refuses to overwrite an existing directory and
 * prints the follow-up steps (pnpm install + dev commands).
 */

import { mkdir, writeFile, access, constants } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../../..");
const DRY = process.argv.includes("--dry-run");

const args = process.argv.slice(2).filter((a) => !a.startsWith("--"));
function flagValue(key) {
  const hit = process.argv.find((a) => a.startsWith(`--${key}=`));
  return hit ? hit.split("=").slice(1).join("=") : null;
}

function pascal(input) {
  return input
    .replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""))
    .replace(/^./, (c) => c.toUpperCase());
}
function kebab(input) {
  return input.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/* ── Templates ─────────────────────────────────────────────── */

function tplPackageJson(name) {
  return `{
  "name": "@dte/${kebab(name)}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "description": "Demon Time Exotics — ${name} surface (generated by @dte/gen-app).",
  "license": "SEE LICENSE IN LICENSE",
  "scripts": {
    "dev": "vite",
    "build": "tsc --noEmit && vite build",
    "build:fast": "vite build",
    "preview": "vite preview",
    "typecheck": "tsc --noEmit",
    "lint": "eslint .",
    "clean": "rm -rf dist .turbo"
  },
  "dependencies": {
    "@dte/shared": "workspace:*",
    "@dte/core": "workspace:*"
  },
  "devDependencies": {
    "@dte/config-eslint": "workspace:*",
    "@dte/config-typescript": "workspace:*",
    "@dte/config-vite": "workspace:*",
    "eslint": "^9.13.0",
    "typescript": "^5.6.3",
    "vite": "^5.4.11"
  }
}
`;
}

function tplTsconfig() {
  return `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "lib": [ "ES2022", "DOM", "DOM.Iterable" ],
    "types": [ "vite/client" ],
    "noEmit": true
  },
  "include": [ "src", "vite.config.ts" ]
}
`;
}

function tplViteConfig(name) {
  return `import { defineConfig } from "vite";
import { webPreset } from "@dte/config-vite";

/**
 * ${name} — Vite config. Uses the shared DTE web preset; tweak the
 * base path if this surface ships under a GitHub Pages project site
 * (like the landing: base "/demon-time-exotics/").
 */
export default defineConfig(
  webPreset({
    base: "/${kebab(name)}/",
    port: 5175
  })
);
`;
}

function tplIndexHtml(name) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#050505" />
    <meta name="description" content="DEMON TIME EXOTICS — THE MESSY SHOW. Hip hop news, drama and commentary from @DTEMONEY448." />
    <title>${name} — DEMON TIME EXOTICS</title>
    <link rel="icon" href="/favicon.ico" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;600;800&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="/src/styles/styles.css" />
  </head>
  <body>
    <header class="topbar">
      <span class="logo">😈 DTE</span>
      <span class="title">${name}</span>
    </header>

    <main class="wrap">
      <section class="hero">
        <p class="eyebrow">THE MESSY SHOW</p>
        <h1 class="title">${name} is live.</h1>
        <p class="sub">Scaffolded by @dte/gen-app. Import your data from @dte/shared and build the surface out.</p>
      </section>
    </main>

    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`;
}

function tplStyles(name) {
  return `/* ${name} — DTE brand tokens (mirrors packages/ui themes) */
:root {
  --fire: #ff5e1a;
  --inferno: #ff2e00;
  --purple: #8b2fd6;
  --gold: #f5a623;
  --ember: #ffb98a;
  --ink: #050505;
  --ink-soft: #0d0d0d;
  --paper: #f4f4f5;
  --muted: #a3a3ab;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  background: var(--ink);
  color: var(--paper);
  font-family: "Inter", system-ui, sans-serif;
  min-height: 100vh;
}

.topbar {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 22px;
  border-bottom: 1px solid rgba(255, 94, 26, 0.25);
  background: rgba(5, 5, 5, 0.9);
  position: sticky;
  top: 0;
}

.topbar .logo {
  font-family: "Bebas Neue", "Arial Narrow", sans-serif;
  font-size: 24px;
  letter-spacing: 2px;
  color: var(--fire);
}

.topbar .title {
  font-size: 13px;
  text-transform: uppercase;
  letter-spacing: 3px;
  color: var(--muted);
}

.wrap { max-width: 980px; margin: 0 auto; padding: 64px 22px; }

.hero .eyebrow {
  color: var(--gold);
  text-transform: uppercase;
  letter-spacing: 4px;
  font-size: 12px;
  font-weight: 800;
  margin-bottom: 10px;
}

.hero .title {
  font-family: "Bebas Neue", "Arial Narrow", sans-serif;
  font-size: clamp(44px, 8vw, 84px);
  line-height: 0.95;
  background: linear-gradient(100deg, var(--fire), var(--inferno) 55%, var(--gold));
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}

.hero .sub { color: var(--muted); margin-top: 16px; max-width: 56ch; }

@media (prefers-reduced-motion: no-preference) {
  .hero .title { animation: flicker-in 0.8s ease-out both; }
  @keyframes flicker-in {
    from { opacity: 0; filter: blur(6px); transform: translateY(10px); }
    to   { opacity: 1; filter: none; transform: none; }
  }
}
`;
}

function tplMain(name) {
  return `import { CHANNEL, CHANNEL_STATS } from "@dte/shared";
import { initCounters, initHub } from "./lib/index.js";

/**
 * ${name} — entry point. Keep it thin: data from @dte/shared, DOM
 * wiring in lib/, structure in index.html.
 */
const statsHost = document.querySelector<HTMLElement>("[data-stats]");
if (statsHost) initCounters(statsHost);

const hubHost = document.querySelector<HTMLElement>("[data-hub]");
if (hubHost) initHub(hubHost);

console.info(
  "%c😈 DEMON TIME EXOTICS — ${name}",
  "color:#ff5e1a;font-weight:bold",
  CHANNEL.name,
  CHANNEL_STATS
);
`;
}

function tplLib() {
  return `import { CHANNEL_STATS, PLATFORMS, formatCompact } from "@dte/shared";

/** Animated counters for the hero stats block (matches landing). */
export function initCounters(host: HTMLElement) {
  const counters = host.querySelectorAll<HTMLElement>("[data-count]");
  counters.forEach((el) => {
    const target = Number(el.dataset.count ?? "0");
    el.textContent = formatCompact(target);
  });
}

/** Platform hub grid from the shared platform registry. */
export function initHub(host: HTMLElement) {
  for (const platform of PLATFORMS) {
    const card = document.createElement("a");
    card.className = "hub-card";
    card.href = platform.url;
    card.target = "_blank";
    card.rel = "noopener noreferrer";
    card.innerHTML = \`<span class="icon">\${platform.icon}</span>
      <span class="name">\${platform.name}</span>
      <span class="note">\${platform.note ?? ""}</span>\`;
    host.append(card);
  }
}

export { CHANNEL_STATS };
`;
}

function tplBarrel(dirName) {
  return `// ${dirName} barrel — generated by @dte/gen-app.
`;
}

/* ── Generator ─────────────────────────────────────────────── */

const FILES = (name) => [
  { path: `apps/${kebab(name)}/package.json`, body: tplPackageJson(name) },
  { path: `apps/${kebab(name)}/tsconfig.json`, body: tplTsconfig() },
  { path: `apps/${kebab(name)}/vite.config.ts`, body: tplViteConfig(name) },
  { path: `apps/${kebab(name)}/index.html`, body: tplIndexHtml(name) },
  { path: `apps/${kebab(name)}/src/styles/styles.css`, body: tplStyles() },
  { path: `apps/${kebab(name)}/src/main.ts`, body: tplMain(name) },
  { path: `apps/${kebab(name)}/src/lib/index.ts`, body: tplLib() },
  { path: `apps/${kebab(name)}/src/components/index.ts`, body: tplBarrel("components") },
  { path: `apps/${kebab(name)}/src/pages/index.ts`, body: tplBarrel("pages") },
  { path: `apps/${kebab(name)}/src/hooks/index.ts`, body: tplBarrel("hooks") }
];

async function main() {
  const rawName = args[0];
  if (!rawName || process.argv.includes("--help")) {
    console.log(`Usage: node tooling/generators/app/index.js <name> [--type web] [--dry-run]

  <name>   app name (PascalCase or kebab-case; "@dte/<kebab>" is the package name)
  --type   only "web" is currently generated (vanilla TS + Vite starter)
  --dry-run  print the plan without writing files`);
    process.exit(rawName ? 0 : 1);
  }

  const type = flagValue("type") ?? "web";
  if (type !== "web") {
    console.error(`Unknown type "${type}" — only "web" starters are generated for now.`);
    console.error("Tauri/Electron/Expo surfaces involve native toolchains; copy the");
    console.error("existing apps/tauri, apps/electron or apps/mobile as templates instead.");
    process.exit(1);
  }

  const name = pascal(rawName);
  const appDir = `apps/${kebab(name)}`;
  const dirAbs = path.join(ROOT, appDir);

  console.log("");
  console.log("😈 DTE app generator");
  console.log(`   name:  @dte/${kebab(name)} (${name})`);
  console.log(`   type:  ${type}`);
  console.log(`   dir:   ${appDir}/ (10 files)`);
  console.log("");

  try {
    await access(dirAbs, constants.F_OK);
    console.error(`💥 ${appDir} already exists — refusing to overwrite.`);
    process.exit(1);
  } catch {
    /* not there — good */
  }

  const plan = FILES(name);
  if (DRY) {
    for (const file of plan) {
      console.log(`  would write ${file.path} (${file.body.length} bytes)`);
    }
    return;
  }

  for (const file of plan) {
    const abs = path.join(ROOT, file.path);
    await mkdir(path.dirname(abs), { recursive: true });
    await writeFile(abs, file.body);
    console.log(`✅ ${file.path}`);
  }

  console.log("");
  console.log("── next ───────────────────────────────────────");
  console.log("  pnpm install                     # link the new workspace");
  console.log(`  pnpm --filter @dte/${kebab(name)} dev   # start the dev server`);
  console.log(`  pnpm --filter @dte/${kebab(name)} build  # ship a dist/`);
  console.log("───────────────────────────────────────────────");
  console.log(`\n🔥 ${name} scaffolded. Make it messy.`);
}

main().catch((error) => {
  console.error("app generator crashed:", error);
  process.exit(1);
});
